name: Python coverage

on:
 push:
   branches:
     - main
     - 'version-**'
   tags: "*"
 pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

env:
  ERT_SHOW_BACKTRACE: 1
  NO_PROJECT_RES: 1


jobs:
  python-test-coverage:
    name: Python Coverage
    timeout-minutes: 40
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test-type: ['ui-test', 'test', 'integration-test']
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: true
        lfs: true

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: "pip"
        cache-dependency-path: |
          pyproject.toml

    - name: Install with dependencies
      run: |
        pip install ".[test]"

    - name: Test GUI
      if: matrix.test-type == 'ui-test'
      env:
        QT_QPA_PLATFORM: 'minimal'
      run: |
        pytest --cov=ieverest -m "ui_test" --cov-report=xml:cov.xml -v

    - name: Test Integration
      if: matrix.test-type == 'integration-test'
      run: |
        pytest tests -n logical --cov=everest -m "integration_test" --cov-report=xml:cov.xml

    - name: Test units
      if: matrix.test-type == 'test'
      run: |
        pytest tests -n logical --cov=everest -m "not ui_test and not integration_test" --cov-report=xml:cov.xml --dist loadgroup -sv

    - name: Upload python coverage to Codecov
      uses: codecov/codecov-action@v4
      id: codecov1
      continue-on-error: true
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
        files: cov.xml
        flags: ${{ matrix.test-type }}
    - name: codecov retry sleep
      if: steps.codecov1.outcome == 'failure'
      run: |
        sleep 30
    - name: Codecov retry
      uses: codecov/codecov-action@v4
      if: steps.codecov1.outcome == 'failure'
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: cov.xml
        fail_ci_if_error: ${{ github.ref == 'refs/heads/main' }}
